### ISSUE TITLE
Google authentikacio

### ISSUE THREAD

**Issue by PumpkinSeed** [flowacademyhu/epsilon-sport-event-organizer#1]
Implementaljatok egy Register/Login feluletet Google OAuth segitsegevel.

**Ez egy gyujto issue, sub-issue letrehozasa az alapjan, hogy ki mit csinal a ti felelosegetek.**

**Comment by borosr** [comment]
A `server/.idea` és a `server/target` mappákat .gitignore-ba kellene tenni

**Comment by PumpkinSeed** [comment]
Resolved by #6
