### ISSUE TITLE
Kupa szervezes

### ISSUE THREAD

**Issue by PumpkinSeed** [flowacademyhu/epsilon-sport-event-organizer#32]
Kupa szervezése
- Egyszeri, egy nap alatt lezajló esemény
- Adott csapatok mérkőznek egymással
- Input
  - Csapatok számossága és neve
  - Pályák száma (egyben csoportok száma)
  - ~~Mérkőzések hossza~~
  - Helyszín
  - Sport típusa (foci egyelore)
  - ~~Szünetek hossza~~
  - ~~Extra szünetek beszúrásának lehetősége (eltérő hossz)~~
  - ~~Menet közben az eredmények bevitele~~
- Kimenet
  - Verseny terv készítése – dinamikusan, a bementi paraméterek állításának megfelelően

**Comment by borosr** [comment]
- [ ] Mérkőzések hossza
- [ ] Sport típusa (foci egyelore)
- [ ] Szünetek hossza
- [ ] Extra szünetek beszúrásának lehetősége (eltérő hossz)
- [ ] Menet közben az eredmények bevitele

**Comment by borosr** [comment]
Expr: 16:30

**Comment by borosr** [comment]
Removed subtasks are going to another issue, 0.4.0
#46
