### ISSUE TITLE
Kupa kovetelmenyek

### ISSUE THREAD

**Issue by PumpkinSeed** [flowacademyhu/epsilon-sport-event-organizer#34]
- [ ] Meghívhatók csapatok
- [ ] Aki létrehozza, az lesz a bajnokság/kupa Szervezője – de egy bajnokságnak/kupának is több szervezője lehet, a Szervező tudja állítani a meghívott csapatok csapattagjait, hogy Szervezővé tehet közülük valakit.
- [ ] Hasonlóak a csapaton belüli Szervező szerephez, itt is 1 szervező legalább mindig kell legyen.

**Comment by VicziTomi** [comment]
adding assignees for fun

**Comment by VicziTomi** [comment]
Megrendelővel történt egyeztetés alapján:
Kupa nyitott, azaz minden csapat (kapitánya) számára van lehetőség jelentkezni adott kupára. Majd a kupa szervezője visszaigazolja a jelentkezést.
Fentiek tükrében módosítanánk az issue leírását!
TY

**Comment by borosr** [comment]
Backend created, frontend fixes needs

**Comment by borosr** [comment]
Expr: 16:30
