### ISSUE TITLE
TeamUiRefresh

### ISSUE THREAD

**Issue by Juhi22** [flowacademyhu/epsilon-sport-event-organizer#40]
team ui refresh bug fix

**Comment by borosr** [comment]
Needs design fixes, ex.: snackbar

**Comment by borosr** [comment]
Expr: 12:00

**Comment by borosr** [comment]
Only must have elements neeeded. Is member exit exists @Juhi22? @PumpkinSeed then this is closeable

**Comment by Juhi22** [comment]
exists @borosr   @PumpkinSeed
