### ISSUE TITLE
Profile page Team view add table

### ISSUE THREAD

**Issue by micsikz** [flowacademyhu/epsilon-sport-event-organizer#41]

**Comment by borosr** [comment]
- [ ] Cup listing
- [ ] Team listing
- [ ] Refactor
- [ ] Desing fix

**Comment by borosr** [comment]
Dependes on: SQL Query of cup list from approved teams

**Comment by borosr** [comment]
Expr: 16:30

**Comment by VicziTomi** [comment]
done, pull request to be sent from feature/T45
